# Generated by Django 6.0.2 on 2026-03-22 05:11

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Fisico'), ('DIGITAL', 'Digital'), ('SPACE', 'Espacio')], max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('technical_description', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ASSIGNED', 'Asignado'), ('MAINTENANCE', 'En mantenimiento'), ('RETIRED', 'Dado de baja')], default='AVAILABLE', max_length=20)),
                ('responsible_area', models.CharField(default='General', max_length=100)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resource.resourcetype')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='resource.resource')),
            ],
            options={
                'ordering': ('-start_date', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('resource',), name='unique_active_assignment_per_resource'), models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('start_date')), _connector='OR'), name='assignment_returned_after_start')],
            },
        ),
    ]
