# Generated by Django 6.0.2 on 2026-04-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('technician', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='resource.resource')),
            ],
            options={
                'ordering': ('-scheduled_date', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_PROGRESS'])), fields=('resource',), name='unique_active_maintenance_per_resource')],
            },
        ),
    ]
